3.7: disable audio patchset, it breaks the build:
	Error: arch/arm/boot/dts/am335x-bonelt.dts:31.8-13 syntax error
	FATAL ERROR: Unable to parse input tree
	make[1]: *** [arch/arm/boot/am335x-bonelt.dtb] Fout 1

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>